#!/usr/bin/env zsh

# run as sudo (for brew install and all...)
sudo -v

# motd
echo -ne "\u001b[38;5;220m"
cat << 'EOF'


      ▄██   ▄   ███▄▄▄▄      ▄█   ▄█▄
      ███   ██▄ ███▀▀▀██▄   ███ ▄███▀
EOF
echo -ne "\u001b[38;5;214m"
cat << 'EOF'
      ███▄▄▄███ ███   ███   ███▐██▀
      ▀▀▀▀▀▀███ ███   ███  ▄█████▀
EOF
echo -ne "\u001b[38;5;39m"
cat << 'EOF'
      ▄██   ███ ███   ███ ▀▀█████▄
      ███   ███ ███   ███   ███▐██▄
EOF
echo -ne "\u001b[38;5;32m"
cat << 'EOF'
      ███   ███ ███   ███   ███ ▀███▄
       ▀█████▀   ▀█   █▀    ███   ▀█▀
                            ▀

EOF
echo -ne "\e[0m"

# bootstrap
ROOT="$HOME/Library/Mobile Documents/com~apple~CloudDocs/.__/dotfiles"
rm -fr $ROOT >> /dev/null # 2>&1
mkdir -p $ROOT >> /dev/null # 2>&1
git clone https://github.com/y-nk/__.git $ROOT >> /dev/null 2>&1
cd $ROOT && . ./.apply
echo "export __=\"$ROOT\"" >> "$HOME/.shellrc"
source $HOME/.zshrc

# allow for future push
git remote remove origin
git remote add origin git@github.com:y-nk/__.git
