#!/usr/bin/env zsh

# run as sudo (for brew install and all...)
sudo -v

# motd
echo -ne "\u001b[38;5;220m"
cat << 'EOF'


      ▄██   ▄   ███▄▄▄▄      ▄█   ▄█▄
      ███   ██▄ ███▀▀▀██▄   ███ ▄███▀
EOF
echo -ne "\u001b[38;5;214m"
cat << 'EOF'
      ███▄▄▄███ ███   ███   ███▐██▀
      ▀▀▀▀▀▀███ ███   ███  ▄█████▀
EOF
echo -ne "\u001b[38;5;39m"
cat << 'EOF'
      ▄██   ███ ███   ███ ▀▀█████▄
      ███   ███ ███   ███   ███▐██▄
EOF
echo -ne "\u001b[38;5;32m"
cat << 'EOF'
      ███   ███ ███   ███   ███ ▀███▄
       ▀█████▀   ▀█   █▀    ███   ▀█▀
                            ▀

EOF
echo -ne "\e[0m"

# bootstrap
__="$HOME/Library/Mobile Documents/com~apple~CloudDocs/.__/dotfiles"
export __=$__

# testing git install
which git >> /dev/null 2>&1
if [ "$?" -eq 1 ];then
  # no git, must install terminal tools
  sudo xcode-select --install
fi

if [ ! -d $__/.git ]; then
  rm -fr $__ >> /dev/null # 2>&1
  mkdir -p $__ >> /dev/null # 2>&1
  git clone https://github.com/y-nk/__.git $__ >> /dev/null 2>&1
fi

cd $__
git pull >> /dev/null # 2>&1
source ./.apply
apply_all
source $HOME/.zshrc

# allow for future push
git remote remove origin
git remote add origin git@github.com:y-nk/__.git
